version: "3.7"

services:
  #Db
  web:
    container_name: 'gitsearch-web-api'
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:80
      - 5001:443
    environment:
      - ConnectionStrings__SqlDb=Server=gitsearch-db-pg15;Database=GitSearch;Username=postgres;Password=postgres;Port=5434;
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db-pg15
  #Db
  db-pg15:
    image: "postgres:latest"
    container_name: 'gitsearch-db-pg15'
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=GitSearch
    volumes:
      - postgres_data_gitsearch:/var/lib/postgresql/data/
  #Db admin
  pg-admin:
    image: 'dpage/pgadmin4'
    container_name: 'gitsearch-db-admin'
    restart: always
    ports:
      - 8070:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@domain.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db-pg15

volumes:
  postgres_data_gitsearch:
  pgadmin-data:
